import { zodToJsonSchema } from 'zod-to-json-schema';
import { z } from 'zod';
import { TOOL_SCHEMAS } from '../schemas/tool-schemas.js';
import { OUTPUT_SCHEMAS } from '../schemas/output-schemas.js';
import { getToolAnnotations, ToolAnnotations } from './annotations.js';

/** JSON Schema 2020-12 dialect URI (MCP spec 2025-11-25 default). */
const JSON_SCHEMA_2020_12 = 'https://json-schema.org/draft/2020-12/schema';

export interface ToolDefinition {
  name: string;
  title: string;
  description: string;
  inputSchema: unknown; // JSON Schema
  outputSchema?: unknown; // JSON Schema
  annotations?: ToolAnnotations;
}

/**
 * Convert a Zod type to a JSON Schema 2020-12 object.
 * zod-to-json-schema targets "jsonSchema2019-09" as the closest supported
 * dialect; we inject $schema 2020-12 manually since 2020-12 is backwards-
 * compatible for the subset of keywords we use.
 */
function toJsonSchema2020(zodType: z.ZodType): Record<string, unknown> {
  const base = zodToJsonSchema(zodType, {
    target: 'jsonSchema2019-09',
    $refStrategy: 'none',
  }) as Record<string, unknown>;
  // Override $schema to 2020-12 — the two dialects are compatible for all
  // keywords generated by zod-to-json-schema (object, array, string, number,
  // boolean, enum, anyOf, $defs).
  base['$schema'] = JSON_SCHEMA_2020_12;
  return base;
}

/**
 * Generate tool definitions combining input and output schemas.
 */
export function generateToolDefinitions(getDescription: (name: string) => string): ToolDefinition[] {
  const entries = Object.entries(TOOL_SCHEMAS);

  return entries.map(([name, schema]) => {
    const inputSchema = toJsonSchema2020(schema as z.ZodType);
    const outputZod = OUTPUT_SCHEMAS[name as keyof typeof OUTPUT_SCHEMAS] as z.ZodType | undefined;
    const outputSchema = outputZod ? toJsonSchema2020(outputZod) : undefined;
    const description = getDescription(name);
    return {
      name,
      title: description,
      description,
      inputSchema,
      outputSchema,
      annotations: getToolAnnotations(name),
    };
  });
}
